// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7Vl8V81wOwdVOk-Psy6E9DTiELW_dF-4',
    appId: '1:490354986336:web:ffa28e3561d4461b5a2205',
    messagingSenderId: '490354986336',
    projectId: 'vcan-c74cc',
    authDomain: 'vcan-c74cc.firebaseapp.com',
    storageBucket: 'vcan-c74cc.firebasestorage.app',
    measurementId: 'G-6BCPCG4Q0F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWXwnv7yetQOxJe-RdaJEtNAat86TTKJg',
    appId: '1:490354986336:android:d0abff7a0a6835585a2205',
    messagingSenderId: '490354986336',
    projectId: 'vcan-c74cc',
    storageBucket: 'vcan-c74cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiCVZTYuGzXbLHa-WPQkhbQE7m6VPFYMk',
    appId: '1:490354986336:ios:d017e11eec14fdca5a2205',
    messagingSenderId: '490354986336',
    projectId: 'vcan-c74cc',
    storageBucket: 'vcan-c74cc.firebasestorage.app',
    iosBundleId: 'com.example.vcan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiCVZTYuGzXbLHa-WPQkhbQE7m6VPFYMk',
    appId: '1:490354986336:ios:d017e11eec14fdca5a2205',
    messagingSenderId: '490354986336',
    projectId: 'vcan-c74cc',
    storageBucket: 'vcan-c74cc.firebasestorage.app',
    iosBundleId: 'com.example.vcan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7Vl8V81wOwdVOk-Psy6E9DTiELW_dF-4',
    appId: '1:490354986336:web:a585d86f898caed25a2205',
    messagingSenderId: '490354986336',
    projectId: 'vcan-c74cc',
    authDomain: 'vcan-c74cc.firebaseapp.com',
    storageBucket: 'vcan-c74cc.firebasestorage.app',
    measurementId: 'G-JJBEY92W7S',
  );
}
